config/routes.rb
Rails.application.routes.draw do
  resources :teachers
  resources :employees
  resources :tollywoods
  resources :students

  root 'employees#new'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :name,:username, presence: {message: "should not be blank"}
  validates :phone, numericality: true
  validates :age, inclusion: {in: 0..100}
  validates :phone, length: { is: 10 }
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email,:phone,:username, uniqueness: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :fname, presence: true
  before_save :fullname
  after_save :add_space
  
  def fullname
    @fname = self.fname
    @lname = self.lname
    self.name = @fname + @lname
  end
  def add_space
    spacename = @fname + " " + @lname
    self.update_column(:name , spacename)
  end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/models/tollywood.rb
class Tollywood < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :age, :phone, :email, :username, :dob)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_id, only: [:show, :edit, :update, :destroy]
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path(@student.id)
    else
      render 'new'
    end
  end

  def show
  end

  def index
    @students = Student.all
  end

  def edit
  end

  def destroy
    if @student.destroy
      redirect_to students_path
    end
  end
  
  def update
    if @edit.update(student_params)
      redirect_to students_path
    end
    
  end
  
  
  private
  
  def student_params
    params.require(:student).permit(:name,:age,:address,:fname,:lname)
  end
  def set_id
    @student = Student.find(params[:id])
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :designation, :email)
    end
end

app/controllers/tollywoods_controller.rb
class TollywoodsController < ApplicationController
  before_action :set_tollywood, only: [:show, :edit, :update, :destroy]

  # GET /tollywoods
  # GET /tollywoods.json
  def index
    @tollywoods = Tollywood.all
  end

  # GET /tollywoods/1
  # GET /tollywoods/1.json
  def show
  end

  # GET /tollywoods/new
  def new
    @tollywood = Tollywood.new
  end

  # GET /tollywoods/1/edit
  def edit
  end

  # POST /tollywoods
  # POST /tollywoods.json
  def create
    @tollywood = Tollywood.new(tollywood_params)

    respond_to do |format|
      if @tollywood.save
        format.html { redirect_to @tollywood, notice: 'Tollywood was successfully created.' }
        format.json { render :show, status: :created, location: @tollywood }
      else
        format.html { render :new }
        format.json { render json: @tollywood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tollywoods/1
  # PATCH/PUT /tollywoods/1.json
  def update
    respond_to do |format|
      if @tollywood.update(tollywood_params)
        format.html { redirect_to @tollywood, notice: 'Tollywood was successfully updated.' }
        format.json { render :show, status: :ok, location: @tollywood }
      else
        format.html { render :edit }
        format.json { render json: @tollywood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tollywoods/1
  # DELETE /tollywoods/1.json
  def destroy
    @tollywood.destroy
    respond_to do |format|
      format.html { redirect_to tollywoods_url, notice: 'Tollywood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tollywood
      @tollywood = Tollywood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tollywood_params
      params.require(:tollywood).permit(:name, :age, :role, :star, :political)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tollywoods_helper.rb
module TollywoodsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Username</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.age %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.email %></td>
        <td><%= employee.username %></td>
        <td><%= employee.dob %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @employee.age %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @employee.username %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @employee.dob %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Batch17</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<center><h1>Hi this is our first project</h1></center>
<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
	<% if @student.errors.any? %>
	<h2><%= pluralize(@student.errors.count, "error") %> prohibited this employee from being saved:</h2>
		<% @student.errors.full_messages.each do |message|%>
			<%= message %>
		<% end %><br />
	<% end %>
	FirstName: <%= f.text_field :fname%><br /><br />
	LastName: <%= f.text_field :lname%><br /><br />
	Age: <%= f.text_field :age %><br /><br />
	Address: <%= f.text_area :address%><br /><br />
	
	<%= f.submit %>
<% end %>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/edit.html.erb
<h1>Update Student Details</h1>

	<%=render 'form' %>

app/views/students/index.html.erb
<h1>Student Records</h1>
<table border = 1px >
	<tr><th>Name</th>
		<th>Age</th>
		<th>Address</th>
		<th>Action</th></tr>
		<% if @students.empty? %>
			<tr><td>-- No Records Found --
			<%= link_to 'new', students_new_path%></td></tr>
		<% else %>
		<% @students.each do |s| %>
			<tr><td><%=s.name%></td>
			<td><%=s.age%></td>
			<td><%=s.address%></td>
			<td><%= link_to 'show' , student_path(s) %>
				<%= link_to 'delete', student_path(s), :method => 'delete', :data => {:confirm => "Are you sure?"}%>
				<%= link_to 'edit' , edit_student_path(s) %>
			</td>
		<% end %>
		<% end %>
</table>

app/views/students/new.html.erb
<h1>Create New Student</h1>

	<%= render 'form'%>

app/views/students/show.html.erb
<h1>Student Information</h1>

<p>Name:<%=@student.name%> </p>
<p>Age: <%=@student.age%></p>
<p>Address:<%=@student.address%> </p>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :designation %><br>
    <%= f.text_field :designation %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Designation</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.designation %></td>
        <td><%= teacher.email %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @teacher.designation %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/tollywoods/_form.html.erb
<%= form_for(@tollywood) do |f| %>
  <% if @tollywood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tollywood.errors.count, "error") %> prohibited this tollywood from being saved:</h2>

      <ul>
      <% @tollywood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :star %><br>
    <%= f.text_field :star %>
  </div>
  <div class="field">
    <%= f.label :political %><br>
    <%= f.check_box :political %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tollywoods/edit.html.erb
<h1>Editing Tollywood</h1>

<%= render 'form' %>

<%= link_to 'Show', @tollywood %> |
<%= link_to 'Back', tollywoods_path %>

app/views/tollywoods/index.html.erb
<center><h1>This Is Header</h1></center>
<p id="notice"><%= notice %></p>

<h1>Listing Tollywoods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Role</th>
      <th>Star</th>
      <th>Political</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tollywoods.each do |tollywood| %>
      <tr>
        <td><%= tollywood.name %></td>
        <td><%= tollywood.age %></td>
        <td><%= tollywood.role %></td>
        <td><%= tollywood.star %></td>
        <td><%= tollywood.political %></td>
        <td><%= link_to 'Show', tollywood %></td>
        <td><%= link_to 'Edit', edit_tollywood_path(tollywood) %></td>
        <td><%= link_to 'Destroy', tollywood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tollywood', new_tollywood_path %>

<center><h1>This Is Footer</h1></center>

app/views/tollywoods/new.html.erb
<h1>New Tollywood</h1>

<%= render 'form' %>

<%= link_to 'Back', tollywoods_path %>

app/views/tollywoods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tollywood.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @tollywood.age %>
</p>

<p>
  <strong>Role:</strong>
  <%= @tollywood.role %>
</p>

<p>
  <strong>Star:</strong>
  <%= @tollywood.star %>
</p>

<p>
  <strong>Political:</strong>
  <%= @tollywood.political %>
</p>

<%= link_to 'Edit', edit_tollywood_path(@tollywood) %> |
<%= link_to 'Back', tollywoods_path %>